### ISSUE TITLE
Collect metric per torrent

### ISSUE THREAD

**Issue by ThomasLachaux** [martabal/qbittorrent-exporter#36]
Hey ! 

Thanks for your awesome tool ❤️ 

An enhancement that would be is awesome is to add the option to collect the metrics per torrent. This would add the possibility to know which torrent are mostly used, etc...

**Comment by martabal** [comment]
Hi !

It already collects metrics per torrent

**Comment by ThomasLachaux** [comment]
I'm totally dumb, thanks !
