### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by Thanzex** [martabal/qbittorrent-exporter#53]
I stumbled upon this issue when I paused my qbittorrent container for a period of time and i noticed this memory usage from the exporter:
![image](https://github.com/martabal/qbittorrent-exporter/assets/24547304/14cc5141-53a0-405a-a745-b0a4a6c8395c)

I was running a previous version of the image, and after noticing #42 I pulled the updated image.
That seemed to initially fix the issue as this looks like a normal Go GC routine
![image](https://github.com/martabal/qbittorrent-exporter/assets/24547304/15fd0681-c86e-44f6-9f06-87165493f89d)

However, here we are a few days later and the memory usage only grew larger
![image](https://github.com/martabal/qbittorrent-exporter/assets/24547304/2b2a36c9-a617-43ac-b7e1-b8d475c4f103)

At this point I'm inclined to believe that the memory leak is still present, with a rate of about 5 MB/h.
I don't see any logging, other than requests coming from prometheus. 

As a temporary workaround I guess I could pause the exporter too when I pause Qbittorrent, but this should be addressed.

**Comment by martabal** [comment]
Hi :wave: 
Thank you for the report, #54 should fix it.
Can you try with the `ghcr.io/martabal/qbittorrent-exporter:pr-54` image ?

**Comment by Thanzex** [comment]
Sure thing! However it will take a bit of time to check if the leak is still present.

**Comment by Thanzex** [comment]
A little more than 24 hours later it seems the issue is solved!
![image](https://github.com/martabal/qbittorrent-exporter/assets/24547304/62ecf3b9-07c5-48f0-93b8-917decafeb3d)

Averaging out the noise there's a slight upwards trend of less than 0.5MB in total, but i guess its SNR is too low to be a valid data point. 
![image](https://github.com/martabal/qbittorrent-exporter/assets/24547304/c1b12f10-17d2-4094-99d9-dc16cbf96391)

I'll update this issue / open a new one if I encounter the problem again.

Thank you!
