### ISSUE TITLE
Cardinality of `qbittorrent_tracker_info`

### ISSUE THREAD

**Issue by markalex2209** [martabal/qbittorrent-exporter#80]
`qbittorrent_tracker_info` has the same cardinality problem as `qbittorrent_torrent_info` does. Labels like `leeches`, `peers` and `seeders` are changing frequently and could cause problems in cardinality. 

Consider disabling `qbittorrent_tracker_info` by default, and enabling it only with `ENABLE_HIGH_CARDINALITY`, [how you already have done with `qbittorrent_torrent_info`](https://github.com/martabal/qbittorrent-exporter/pull/76).

Additionally, if you see this information useful, you might consider exposing those values as proper metrics. Something like `qbittorrent_tracker_leeches`, `qbittorrent_tracker_peers`, etc. 
Only label I'm unsure is `message`: if it changes rarely, I guess it's acceptable to give it own metric. But if frequent - I'd leave it out of metrics, and allow something like Loki gather that information.

**Comment by martabal** [comment]
Hey :wave: 

Thanks for the report!
